### ISSUE TITLE
can't see if an index is used using EXPLAIN

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#647]
Regular mysql add extra column with something like `Using index condition` in explain. But I don't see it with gitbase. Though indexes where applied (because the query became much faster).

**Comment by ajnavarro** [comment]
We implemented a custom EXPLAIN format, the tree format: (`EXPLAIN format=tree`)

Implement mysql EXPLAIN standard output is really cumbersome, and I'm not sure about is worth it the effort.

@smola, @mcuadros WDYT?

**Comment by smacker** [comment]
Hm. I don't see it in `EXPLAIN format=tree`.

```
$ ./gitbase version
gitbase (v0.18.0-beta.3) - build 11-27-2018_11_31_37
```

Examples from:
https://github.com/src-d/gitbase/blob/master/docs/using-gitbase/optimize-queries.md#indexes

Index on language is created:
```
mysql> show indexes from files \G;
*************************** 1. row ***************************
        Table: files
   Non_unique: 1
     Key_name: files_lang_idx
 Seq_in_index: 1
  Column_name: NULL
    Collation: NULL
  Cardinality: 0
     Sub_part: 0
       Packed: NULL
         Null:
   Index_type: pilosa
      Comment:
Index_comment:
      Visible: YES
   Expression: language(files.file_path, files.blob_content)
1 row in set (0.00 sec)
```

Run explain for queries that should use index:
```
mysql> explain format=tree SELECT file_path FROM files WHERE language(file_path, blob_content) = 'Go';
+------+
| plan |
+------+
| Exchange(parallelism=4) |
|  └─ Project(files.file_path) |
|      └─ Table(files) |
|          ├─ Column(repository_id, TEXT, nullable=false) |
|          ├─ Column(file_path, TEXT, nullable=false) |
|          ├─ Column(blob_hash, TEXT, nullable=false) |
|          ├─ Column(tree_hash, TEXT, nullable=false) |
|          ├─ Column(tree_entry_mode, TEXT, nullable=false) |
|          ├─ Column(blob_content, BLOB, nullable=false) |
|          └─ Column(blob_size, INT64, nullable=false) |
+------+
```

Explain query that shouldn't use index.
```
mysql> explain format=tree SELECT file_path FROM files WHERE language(file_path, blob_content) = SUBSTRING(file_path, 0, 2);
+------+
| plan |
+------+
| Exchange(parallelism=4) |
|  └─ Project(files.file_path) |
|      └─ Table(files) |
|          ├─ Column(repository_id, TEXT, nullable=false) |
|          ├─ Column(file_path, TEXT, nullable=false) |
|          ├─ Column(blob_hash, TEXT, nullable=false) |
|          ├─ Column(tree_hash, TEXT, nullable=false) |
|          ├─ Column(tree_entry_mode, TEXT, nullable=false) |
|          ├─ Column(blob_content, BLOB, nullable=false) |
|          └─ Column(blob_size, INT64, nullable=false) |
+------+
10 rows in set (0.00 sec)
```

I don't see any difference.


Just to make sure the index isn't in process of creating:
```
mysql> SHOW PROCESSLIST \G;
*************************** 1. row ***************************
     Id: 26
   User: root
   Host: 127.0.0.1:52228
     db: gitbase
Command: query
   Time: 0
  State: running
   Info: SHOW PROCESSLIST
1 row in set (0.00 sec)

ERROR:
No query specified
```
